# PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/animals

###

POST http://localhost:3333/animals
Content-Type: application/json

{
    "name": "Sansão",
    "raça": "Border Collie",
    "idade": "5",
    "tutor": "Lara"
}

###

PUT http://localhost:3333/animals/{id}
Content-Type: application/json

{
    "name": "Sansão Atualizado",
    "raça": "SRD",
    "idade": "4",
    "tutor": "Titicia"
}

###

DELETE http://localhost:3333/animals/{id}
